<?php

/*
 * TRIM rule names
 * V1, 2021-02-18
 */

$trim_medication_rules = json_decode('[{"medication_rule_id": 1, "medication_rule_name": "ALENDRONATE", "medication_rule_logic": ""},
{"medication_rule_id": 2, "medication_rule_name": "ALLOPURINOL", "medication_rule_logic": ""},
{"medication_rule_id": 3, "medication_rule_name": "ALPRAZOLAM", "medication_rule_logic": ""},
{"medication_rule_id": 4, "medication_rule_name": "AMANTADINE", "medication_rule_logic": ""},
{"medication_rule_id": 5, "medication_rule_name": "AMITRIPTYLINE", "medication_rule_logic": ""},
{"medication_rule_id": 6, "medication_rule_name": "ASPIRIN", "medication_rule_logic": ""},
{"medication_rule_id": 7, "medication_rule_name": "ATENOLOL", "medication_rule_logic": ""},
{"medication_rule_id": 8, "medication_rule_name": "CARVEDILOL", "medication_rule_logic": ""},
{"medication_rule_id": 9, "medication_rule_name": "CHLORDIAZEPOXIDE", "medication_rule_logic": ""},
{"medication_rule_id": 10, "medication_rule_name": "CHLORPHENIRAMINE", "medication_rule_logic": ""},
{"medication_rule_id": 11, "medication_rule_name": "CHLORPROPRAMIDE", "medication_rule_logic": ""},
{"medication_rule_id": 12, "medication_rule_name": "CITALOPRAM ", "medication_rule_logic": ""},
{"medication_rule_id": 13, "medication_rule_name": "CLONAZEPAM", "medication_rule_logic": ""},
{"medication_rule_id": 14, "medication_rule_name": "CLOPIDOGREL", "medication_rule_logic": ""},
{"medication_rule_id": 15, "medication_rule_name": "CODEINE", "medication_rule_logic": ""},
{"medication_rule_id": 16, "medication_rule_name": "CYCLOBENZAPRINE", "medication_rule_logic": ""},
{"medication_rule_id": 17, "medication_rule_name": "DESIPRAMINE", "medication_rule_logic": ""},
{"medication_rule_id": 18, "medication_rule_name": "DIAZEPAM", "medication_rule_logic": ""},
{"medication_rule_id": 19, "medication_rule_name": "DICLOFENAC", "medication_rule_logic": ""},
{"medication_rule_id": 20, "medication_rule_name": "DIGOXIN", "medication_rule_logic": ""},
{"medication_rule_id": 21, "medication_rule_name": "DILTIAZEM", "medication_rule_logic": ""},
{"medication_rule_id": 22, "medication_rule_name": "DIMENHYDRINATE", "medication_rule_logic": ""},
{"medication_rule_id": 23, "medication_rule_name": "DIPHENHYDRAMINE", "medication_rule_logic": ""},
{"medication_rule_id": 24, "medication_rule_name": "DOXYLAMINE", "medication_rule_logic": ""},
{"medication_rule_id": 25, "medication_rule_name": "ESOMEPRAZOLE", "medication_rule_logic": ""},
{"medication_rule_id": 26, "medication_rule_name": "ESZOPICLONE", "medication_rule_logic": ""},
{"medication_rule_id": 27, "medication_rule_name": "ETODOLAC", "medication_rule_logic": ""},
{"medication_rule_id": 28, "medication_rule_name": "FAMOTIDINE", "medication_rule_logic": ""},
{"medication_rule_id": 29, "medication_rule_name": "FENTANYL", "medication_rule_logic": ""},
{"medication_rule_id": 30, "medication_rule_name": "GABAPENTIN ", "medication_rule_logic": ""},
{"medication_rule_id": 31, "medication_rule_name": "GALANTAMINE", "medication_rule_logic": ""},
{"medication_rule_id": 32, "medication_rule_name": "GLYBURIDE", "medication_rule_logic": ""},
{"medication_rule_id": 33, "medication_rule_name": "HYDROCHLOROTHIAZIDE", "medication_rule_logic": ""},
{"medication_rule_id": 34, "medication_rule_name": "HYDROCODONE", "medication_rule_logic": ""},
{"medication_rule_id": 35, "medication_rule_name": "HYDROMORPHONE", "medication_rule_logic": ""},
{"medication_rule_id": 36, "medication_rule_name": "HYDROXYZINE", "medication_rule_logic": ""},
{"medication_rule_id": 37, "medication_rule_name": "IBUPROFEN", "medication_rule_logic": ""},
{"medication_rule_id": 38, "medication_rule_name": "IMIPRAMINE", "medication_rule_logic": ""},
{"medication_rule_id": 39, "medication_rule_name": "INDOMETHACIN", "medication_rule_logic": ""},
{"medication_rule_id": 40, "medication_rule_name": "LABETALOL", "medication_rule_logic": ""},
{"medication_rule_id": 41, "medication_rule_name": "LANSOPRAZOLE", "medication_rule_logic": ""},
{"medication_rule_id": 42, "medication_rule_name": "LORAZEPAM", "medication_rule_logic": ""},
{"medication_rule_id": 43, "medication_rule_name": "MELOXICAM", "medication_rule_logic": ""},
{"medication_rule_id": 44, "medication_rule_name": "MEMANTINE", "medication_rule_logic": ""},
{"medication_rule_id": 45, "medication_rule_name": "METFORMIN", "medication_rule_logic": ""},
{"medication_rule_id": 46, "medication_rule_name": "METHADONE", "medication_rule_logic": ""},
{"medication_rule_id": 47, "medication_rule_name": "METHOCARBAMOL", "medication_rule_logic": ""},
{"medication_rule_id": 48, "medication_rule_name": "METOCLOPRAMIDE", "medication_rule_logic": ""},
{"medication_rule_id": 49, "medication_rule_name": "METOPROLOL", "medication_rule_logic": ""},
{"medication_rule_id": 50, "medication_rule_name": "MORPHINE", "medication_rule_logic": ""},
{"medication_rule_id": 51, "medication_rule_name": "NABUMETONE", "medication_rule_logic": ""},
{"medication_rule_id": 52, "medication_rule_name": "NAPROXEN", "medication_rule_logic": ""},
{"medication_rule_id": 53, "medication_rule_name": "NORTRIPTYLINE", "medication_rule_logic": ""},
{"medication_rule_id": 54, "medication_rule_name": "OMEPRAZOLE", "medication_rule_logic": ""},
{"medication_rule_id": 55, "medication_rule_name": "OXAZEPAM", "medication_rule_logic": ""},
{"medication_rule_id": 56, "medication_rule_name": "OXYBUTYNIN", "medication_rule_logic": ""},
{"medication_rule_id": 57, "medication_rule_name": "OXYCODONE", "medication_rule_logic": ""},
{"medication_rule_id": 58, "medication_rule_name": "PANTOPRAZOLE", "medication_rule_logic": ""},
{"medication_rule_id": 59, "medication_rule_name": "PIROXICAM", "medication_rule_logic": ""},
{"medication_rule_id": 60, "medication_rule_name": "PROCHLORPERAZINE", "medication_rule_logic": ""},
{"medication_rule_id": 61, "medication_rule_name": "PROMETHAZINE", "medication_rule_logic": ""},
{"medication_rule_id": 62, "medication_rule_name": "PROPRANOLOL", "medication_rule_logic": ""},
{"medication_rule_id": 63, "medication_rule_name": "RABEPRAZOLE", "medication_rule_logic": ""},
{"medication_rule_id": 64, "medication_rule_name": "RANITIDINE", "medication_rule_logic": ""},
{"medication_rule_id": 65, "medication_rule_name": "ROSUVASTATIN", "medication_rule_logic": ""},
{"medication_rule_id": 66, "medication_rule_name": "SPIRONOLACTONE", "medication_rule_logic": ""},
{"medication_rule_id": 67, "medication_rule_name": "SULINDAC", "medication_rule_logic": ""},
{"medication_rule_id": 68, "medication_rule_name": "TEMAZEPAM", "medication_rule_logic": ""},
{"medication_rule_id": 69, "medication_rule_name": "TOLTERODINE", "medication_rule_logic": ""},
{"medication_rule_id": 70, "medication_rule_name": "TRAMADOL", "medication_rule_logic": ""},
{"medication_rule_id": 71, "medication_rule_name": "TRIAMTERENE", "medication_rule_logic": ""},
{"medication_rule_id": 72, "medication_rule_name": "TROSPIUM", "medication_rule_logic": ""},
{"medication_rule_id": 73, "medication_rule_name": "VERAPAMIL", "medication_rule_logic": ""},
{"medication_rule_id": 74, "medication_rule_name": "WARFARIN", "medication_rule_logic": ""},
{"medication_rule_id": 75, "medication_rule_name": "ZALEPLON", "medication_rule_logic": ""},
{"medication_rule_id": 76, "medication_rule_name": "ZOLPIDEM", "medication_rule_logic": ""}]');

$trim_disease_rules = json_decode('[{"disease_rule_id": 1, "disease_rule_name": "ATRIAL FIBRILLATION", "disease_rule_logic": ""},
{"disease_rule_id": 2, "disease_rule_name": "BPH/HISTORY OF URINARY RETENTION", "disease_rule_logic": ""},
{"disease_rule_id": 3, "disease_rule_name": "CAD OR MI", "disease_rule_logic": ""},
{"disease_rule_id": 4, "disease_rule_name": "CANCER", "disease_rule_logic": ""},
{"disease_rule_id": 5, "disease_rule_name": "CHRONIC KIDNEY DISEASE", "disease_rule_logic": ""},
{"disease_rule_id": 6, "disease_rule_name": "CONGESTIVE HEART FAILURE", "disease_rule_logic": ""},
{"disease_rule_id": 7, "disease_rule_name": "COPD", "disease_rule_logic": ""},
{"disease_rule_id": 8, "disease_rule_name": "DEMENTIA", "disease_rule_logic": ""},
{"disease_rule_id": 9, "disease_rule_name": "DIABETES", "disease_rule_logic": ""},
{"disease_rule_id": 10, "disease_rule_name": "FALLS", "disease_rule_logic": ""},
{"disease_rule_id": 11, "disease_rule_name": "GI BLEED", "disease_rule_logic": ""},
{"disease_rule_id": 12, "disease_rule_name": "HEART FAILURE", "disease_rule_logic": ""},
{"disease_rule_id": 14, "disease_rule_name": "HYPERTENSION", "disease_rule_logic": ""},
{"disease_rule_id": 15, "disease_rule_name": "PARKINSONISM", "disease_rule_logic": ""},
{"disease_rule_id": 16, "disease_rule_name": "PEPTIC ULCER DISEASE", "disease_rule_logic": ""},
{"disease_rule_id": 17, "disease_rule_name": "PERIPHERAL ARTERY DISEASE", "disease_rule_logic": ""},
{"disease_rule_id": 18, "disease_rule_name": "STROKE", "disease_rule_logic": ""}]');

print "<p>Hi Mom</p>";
